apiVersion: v1
kind: PersistentVolume
metadata:
  name: anaconda-gpu-vol
  namespace: anaconda-gpu
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.171.199
    path: /ifs/eng/dsp/docker/data-vol
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: anaconda-data-lake-gpu-vol
  namespace: anaconda-gpu
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.171.199
    path: /ifs/eng/dsp/hadoop/d
